import { VESSEL_FAMILIES } from './vessel-catalog.js';
// Fictional working-coast balance data; all money is game CAD.
export const ECONOMY = {
  startCash: 20000,
  fuelPrice: 2.15,
  landingFee: 85,
  insuranceDaily: 65,
  insuranceCover: 0.7,
  licenceCost: 240,
  licenceDays: 12,
  interest: 0.003,
  creditBase: 15000,
  creditPerRank: 25000,
  developmentCredit: true,
  dockWage: 420,
  restRecovery: 0.6,
  restDayRecovery: 0.22,
  earlyFatigue: 0.06,
  workFatigue: 0.00105,
  bagSeconds: 45,
  crewShare: 0.4,
  contactEarnings: [0, 250, 500],
  contactSafeDays: [0, 3, 6],
  // Experienced divers want evidence of a productive, safe operation rather than rank alone.
  contactGoals: [
    null,
    {
      totalCatch: 5000,
      bestLoad: 1400,
      bestReturn: 2500,
      totalRevenue: 8000,
      longestDayMinutes: 360,
      safeDays: 3,
      maximumLongDayFatigue: 0.72,
    },
    {
      totalCatch: 15000,
      bestLoad: 2800,
      bestReturn: 6500,
      totalRevenue: 30000,
      longestDayMinutes: 480,
      safeDays: 6,
      maximumLongDayFatigue: 0.62,
    },
  ],
  resaleFraction: 0.5,
  auxTankLitres: 120,
};
export const FLEET = {
  basic: {
    price: 15000,
    rank: 0,
    capacity: 7500,
    length: 10,
    width: 4,
    mass: 6500,
    fuelCapacity: 480,
    travelBurn: 15,
    maxSpeed: 10 / 1.943844,
    cabinFore: 1.8,
    waveTolerance: 1,
  },
  thruster: {
    price: 52000,
    rank: 1,
    capacity: 8500,
    length: 12,
    width: 4.5,
    mass: 10000,
    fuelCapacity: 720,
    travelBurn: 15,
    maxSpeed: 10 / 1.943844,
    cabinFore: 2.2,
    waveTolerance: 1.45,
    windage: 0.042,
  },
  sterndrive: {
    price: 44000,
    rank: 0,
    capacity: 6000,
    length: 9,
    width: 3.5,
    mass: 5100,
    fuelCapacity: 440,
    travelBurn: 25,
    maxSpeed: 14 / 1.943844,
    cabinFore: 1.4,
    waveTolerance: 0.9,
  },
  outboard: {
    price: 15000,
    rank: 0,
    capacity: 3000,
    length: 7,
    width: 2.8,
    mass: 3900,
    fuelCapacity: 360,
    travelBurn: 15,
    maxSpeed: 25 / 1.943844,
    loadedSpeed: 15 / 1.943844,
    cabinFore: 1.1,
    waveTolerance: 0.72,
  },
  jet: {
    price: 68000,
    rank: 1,
    capacity: 10000,
    length: 12.5,
    width: 4.6,
    mass: 6900,
    fuelCapacity: 640,
    travelBurn: 35,
    maxSpeed: 10 / 1.943844,
    cabinFore: 1.6,
    waveTolerance: 1.1,
  },
  twinjet: {
    price: 145000,
    rank: 2,
    capacity: 16000,
    length: 15.5,
    width: 5.2,
    mass: 16500,
    fuelCapacity: 1240,
    travelBurn: 70,
    maxSpeed: 18 / 1.943844,
    cabinFore: 2.5,
    waveTolerance: 1.8,
    windage: 0.05,
  },
};
// Individually balanced alternatives, with trade-offs in both directions.
const SISTERS = {
  basic: {
    price: 27500,
    capacity: 6200,
    fuelCapacity: 580,
    travelBurn: 18,
    knots: 12,
    draft: 2.3,
    maneuverability: 1.18,
    durability: 0.82,
  },
  thruster: {
    price: 39000,
    capacity: 9800,
    fuelCapacity: 540,
    travelBurn: 12,
    knots: 8,
    draft: 1.75,
    maneuverability: 0.83,
    durability: 1.22,
  },
  sterndrive: {
    price: 61000,
    capacity: 4700,
    fuelCapacity: 620,
    travelBurn: 29,
    knots: 17,
    draft: 1.7,
    maneuverability: 0.88,
    durability: 1.16,
  },
  outboard: {
    price: 24000,
    capacity: 4100,
    fuelCapacity: 270,
    travelBurn: 19,
    knots: 21,
    loadedSpeed: 13 / 1.943844,
    draft: 2.25,
    maneuverability: 1.16,
    durability: 0.87,
  },
  jet: {
    price: 53000,
    capacity: 8300,
    fuelCapacity: 790,
    travelBurn: 31,
    knots: 13,
    draft: 1.2,
    maneuverability: 1.13,
    durability: 0.84,
  },
  twinjet: {
    price: 188000,
    capacity: 18200,
    fuelCapacity: 960,
    travelBurn: 78,
    knots: 16,
    draft: 0.8,
    maneuverability: 0.86,
    durability: 1.24,
  },
};
export const FLEET_ORDER = VESSEL_FAMILIES.flatMap(([id]) => [id, id + '-sister']);
for (const [id] of VESSEL_FAMILIES) {
  const base = FLEET[id];
  const { knots, ...variant } = SISTERS[id];
  FLEET[id + '-sister'] = {
    ...base,
    ...variant,
    maxSpeed: knots / 1.943844,
    length: base.length + 0.2,
    mass: Math.round(base.mass * 1.04),
  };
}
export const CREW = [
  {
    id: 'ada',
    name: 'Ada Chen',
    portraitSrc: './assets/crew/ada.png',
    rank: 0,
    colour: '#b46e46',
    bio: 'Ada checks the ground before committing, keeps the deck tidy, and rarely wastes air. Her quiet pre-dive checklist is famous for being right.',
    searchSpeed: 0.9,
    harvestRate: 1,
    airUse: 1,
    awareness: 9.144,
    holdCurrentKnots: 2,
    judgement: 0.95,
    reliability: 0.97,
  },
  {
    id: 'milo',
    name: 'Milo Ward',
    portraitSrc: './assets/crew/milo.png',
    rank: 0,
    colour: '#648c9c',
    bio: 'Milo used to race open-water swims. He is fast across the bottom and quick to bag, but burns air and may chase a thin patch too long.',
    searchSpeed: 1.08,
    harvestRate: 1.03,
    airUse: 1.13,
    awareness: 8.5,
    holdCurrentKnots: 1.85,
    judgement: 0.8,
    reliability: 0.94,
  },
  {
    id: 'nell',
    name: 'Nell Fraser',
    portraitSrc: './assets/crew/nell.png',
    rank: 0,
    colour: '#879262',
    bio: 'Nell is a patient reef reader with sharp awareness and clean picking. She never rushes, then quietly notices the good product has moved.',
    searchSpeed: 0.86,
    harvestRate: 1.1,
    airUse: 0.91,
    awareness: 10,
    holdCurrentKnots: 2.1,
    judgement: 0.98,
    reliability: 0.98,
  },
  {
    id: 'roy',
    name: 'Roy Bell',
    portraitSrc: './assets/crew/roy.png',
    rank: 0,
    colour: '#b48650',
    bio: 'Roy fills bags faster than anyone near the harbour and owns the loudest compressor. He thrives on dense ground and treats dive tables as suggestions.',
    searchSpeed: 0.83,
    harvestRate: 1.3,
    airUse: 1.3,
    awareness: 8,
    holdCurrentKnots: 2,
    judgement: 0.86,
    reliability: 0.93,
  },
  {
    id: 'inez',
    name: 'Inez Brooks',
    portraitSrc: './assets/crew/inez.png',
    rank: 1,
    colour: '#609386',
    bio: 'Inez grew up rowing tidal channels. She holds position in strong current, keeps a deliberate route, and gets calmer when the water starts moving.',
    searchSpeed: 0.95,
    harvestRate: 1.12,
    airUse: 0.94,
    awareness: 10.5,
    holdCurrentKnots: 2.7,
    judgement: 0.97,
    reliability: 0.98,
  },
  {
    id: 'robinson',
    name: 'R. Robinson',
    portraitSrc: './assets/crew/robinson.png',
    rank: 1,
    colour: '#bba260',
    bio: 'R. Robinson never hurries and somehow makes the last breath last longer. Their exceptional awareness rewards patient work and mildly annoys clocks.',
    searchSpeed: 0.92,
    harvestRate: 1.06,
    airUse: 0.76,
    awareness: 11,
    holdCurrentKnots: 2.2,
    judgement: 0.98,
    reliability: 0.97,
  },
  {
    id: 'murphy',
    name: 'Pat Murphy',
    portraitSrc: './assets/crew/murphy.png',
    rank: 2,
    colour: '#887da4',
    bio: 'Pat is an excellent, very fast picker with strong all-round water skills. They carry three identical regulator bags and will not explain why.',
    searchSpeed: 1.05,
    harvestRate: 1.35,
    airUse: 0.93,
    awareness: 11.5,
    holdCurrentKnots: 2.4,
    judgement: 0.91,
    reliability: 0.88,
  },
  {
    id: 'dave',
    name: 'Dave Kaimana',
    portraitSrc: './assets/crew/dave.png',
    rank: 2,
    colour: '#578fa2',
    bio: 'Dave is a broad-shouldered veteran, quick and air-efficient in hard current. He is almost never wrong, and a tiny restaurant still asks after him.',
    searchSpeed: 1.06,
    harvestRate: 1.32,
    airUse: 0.83,
    awareness: 12,
    holdCurrentKnots: 2.8,
    judgement: 0.99,
    reliability: 0.99,
  },
];
export const UPGRADES = [
  {
    id: 'clock-brass',
    name: 'Brass wheel clock',
    price: 120,
    rank: 0,
    slot: 'timepiece',
    detail:
      'Traditional hands in a brass bezel. Choose this purchased face in Arrange UI layout → Timepiece. Decoration only; the standard red digital clock stays available.',
  },
  {
    id: 'clock-urchin',
    name: 'Urchin clock',
    price: 280,
    rank: 0,
    slot: 'timepiece',
    detail:
      'A purple spiny clock for the wheelhouse. Choose its face in Arrange UI layout → Timepiece. Same ship’s time; no gameplay bonus.',
  },
  {
    id: 'clock-tide',
    name: 'Tide-face clock',
    price: 400,
    rank: 0,
    slot: 'timepiece',
    detail:
      'A sea-blue novelty timepiece. It tells ship’s time, not the tide forecast. Choose its face in Arrange UI layout → Timepiece.',
  },
  {
    id: 'bowthruster',
    name: 'Bow thruster retrofit',
    price: 20000,
    rank: 0,
    slot: 'bow',
    detail:
      'Fits every boat. Lateral push at the bow at low speed; hold left stick left/right. Boats with a factory thruster can also fit this package.',
  },
  {
    id: 'nitrox',
    name: 'Nitrox dive system',
    price: 85000,
    rank: 2,
    slot: 'working deck',
    detail:
      'Premium dive-gas system: 60% more fictional depth-time allowance and 20% longer tank endurance. Adds one second to each entry from deck. Surface recovery still matters.',
  },
  {
    id: 'plotter',
    slot: 'console',
    name: 'Recording chartplotter',
    price: 1800,
    rank: 0,
    detail: 'Keeps depth tracks and reef observations between trips.',
  },
  {
    id: 'lights',
    slot: 'mast',
    name: 'Deck and working lights',
    price: 1100,
    rank: 0,
    detail:
      'Lights the port recovery area and a forward-facing cone after dark; restores normal night pickup range.',
  },
  {
    id: 'torch',
    slot: 'dive gear',
    name: 'Diver flashlights',
    price: 450,
    rank: 0,
    detail:
      'A flashlight for each diver. Allows diving after dark (19:30–06:00). Night work builds fatigue twice as fast.',
  },
  {
    id: 'hoist',
    slot: 'working deck',
    name: 'Hydraulic bag hauler',
    price: 3400,
    rank: 1,
    detail: 'Shortens bag handling from 3 to 2.2 seconds.',
  },
  {
    id: 'radar',
    slot: 'mast',
    name: 'Compact radar',
    price: 4200,
    rank: 1,
    detail: 'Reports nearby surface hazards through fog and darkness.',
  },
  {
    id: 'forecast',
    slot: 'console',
    name: 'Coastal weather receiver',
    price: 2200,
    rank: 1,
    detail: 'More useful timing and confidence in the weather outlook.',
  },
  {
    id: 'scanner',
    slot: 'console',
    name: 'Forward bottom scanner',
    price: 8500,
    rank: 2,
    detail: 'Samples a narrow fan ahead. Bottom and habitat clues, not exact catch.',
  },
  {
    id: 'stabilizer',
    slot: 'hull',
    name: 'Working-boat stabilizers',
    price: 6400,
    rank: 1,
    detail: 'Reduces wave yaw and improves rough-water working comfort.',
  },
  {
    id: 'tank',
    slot: 'aft deck',
    name: 'Auxiliary fuel tank',
    price: 2800,
    rank: 0,
    detail: 'Adds a fixed 120 L tank. Fuel carried adds weight and slightly slows acceleration.',
  },
  {
    id: 'glasses',
    slot: 'skipper',
    name: 'Polarised skipper glasses',
    price: 180,
    rank: 0,
    detail: 'Makes nearby shallow reefs easier to read in daylight.',
  },
];
export const RANKS = [
  { xp: 0, name: 'Local hand' },
  { xp: 1200, name: 'Working skipper' },
  { xp: 4500, name: 'Coastal skipper' },
  { xp: 12000, name: 'Old hand' },
];
export const rankOf = (c) =>
  Math.max(
    0,
    RANKS.findLastIndex((r) => c.xp >= r.xp),
  );
export function roll(seed, salt = 0) {
  let n = (seed + Math.imul(salt, 2654435761)) >>> 0;
  n = Math.imul(n ^ (n >>> 16), 0x21f0aaad);
  n = Math.imul(n ^ (n >>> 15), 0x735a2d97);
  return ((n ^ (n >>> 16)) >>> 0) / 4294967296;
}
export { money } from './format.js';
export const cents = (n) => Math.round(n * 100) / 100;
