export const TITLES = {
  market: 'BUYER MARKET',
  'deck-catch': 'CATCH ON DECK',
  'equipment-controls': 'EQUIPMENT SWITCHES',
  'touch-options': 'TOUCHSCREEN OPTIONS',
  intro: 'A TALKING TO BY FRANK',
  introchart: 'FRANK’S COVE',
  intropause: 'DAY 0 · ABOARD WITH FRANK',
  purchase: 'CONFIRM PURCHASE',
  patrol: 'DFO PATROL',
  archives: 'LOAD GAME',
  radio: 'RADIO HISTORY',
  conditions: 'WEATHER OUTLOOK',
  knowledge: 'LOCAL CHART',
  assists: 'UI / DIFFICULTY OPTIONS',
  fleetboard: 'THE WORKING FLEET',
  harbour: 'HARBOUR',
  crew: 'CREW',
  fleet: 'BOATYARD',
  yourboat: 'YOUR BOAT',
  outfit: 'EQUIPMENT',
  accounts: 'ACCOUNTS',
  logbook: 'SKIPPER LOGBOOK',
  emergency: 'EMERGENCY — FISHING ENDED',
  boatyard: 'PROTOTYPE BOATYARD',
  almanac: 'TIDE & CURRENT ALMANAC',
  pause: 'PAUSED',
  'skipper-stuff': 'SKIPPER STUFF',
  'debug-mode': 'DEBUG MODE',
  'debug-time': 'DEBUG · SET TIME',
  'debug-weather': 'DEBUG · SET WEATHER',
  'debug-tide': 'DEBUG · SET TIDE HEIGHT',
  bindings: 'CONTROLS / REMAPPING',
  instructions: 'DIVER ORDERS',
  help: 'SKIPPER’S NOTES',
  exit: 'SESSION ENDED',
  chart: 'CHART & WORKING DAY',
  departure: 'DEPARTURE PLAN',
  summary: 'BACK AT HARBOUR',
  controller: 'CONTROLLER SETUP',
};
